name: Build eneaproject/backup-container
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.0
    - name: Dockerhub login
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "${DOCKERHUB_TOKEN}" | docker login --username ${DOCKERHUB_USER} --password-stdin
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3.1.0
    - name: Build dockerfile (with push)
      run: |
        docker buildx build                                      \
          --platform=linux/amd64,linux/arm64                     \
          --output type=image,push=true                          \
          --file ./Dockerfile                                    \
          --tag "eneaproject/backup-container":${GITHUB_SHA:0:7} \
          --tag "eneaproject/backup-container":latest            \
          .
